name: DevSecOps Pipeline

on:
  push:
    branches: [main]
    paths-ignore:
      - 'k8s/**'
      - 'docs/**'
      - '**/*.md'
  workflow_dispatch:

jobs:
  Code-Quality:
    uses: ./.github/workflows/code_quality.yml


  Secret-Scan:
    uses: ./.github/workflows/secret_scanning.yml


  Dependency-Scan:
    uses: ./.github/workflows/dependency_scanning.yml


  Dockerfile-linting:
    uses: ./.github/workflows/dockerfile_scanning.yml


  Docker-image-scan:
    needs: [Code-Quality, Secret-Scan, Dependency-Scan, Dockerfile-linting]
    uses: ./.github/workflows/docker_image_scan.yml
    secrets: inherit
    